name: "player"
imagesIdle: ["resources/sprite data/images/standsprite.png"]
imagesRight: ["resources/sprite data/images/spriterunright1.png",
"resources/sprite data/images/spriterunright2.png",
"resources/sprite data/images/spriterunright3.png"]
imagesLeft: ["resources/sprite data/images/spriterunleft1.png",
"resources/sprite data/images/spriterunleft2.png",
"resources/sprite data/images/spriterunleft3.png"]
imagesInAirLeft: ["resources/sprite data/images/spriterunright1.png",
"resources/sprite data/images/spriterunright2.png",
"resources/sprite data/images/spriterunright3.png"]
imagesInAirRight: ["resources/sprite data/images/spriterunleft1.png",
"resources/sprite data/images/spriterunleft2.png",
"resources/sprite data/images/spriterunleft3.png"]
xStart: 100.0
yStart: 100.0
type: "PLAYER"